# -*- coding: utf-8 -*-
"""
train_and_evaluate_ours.py

Main reproduction script for the proposed method reported in Table 2 and Table 3 of the manuscript:
"A Multi-Scale Collaborative Optimization Approach for Infrared Target Detection of Electrical Apparatus in Switchgear Cabinets".

This script corresponds to the final YOLOv10m-based model with:
1. Target Aug: minority-class-oriented training-list resampling/augmentation;
2. Class Weight: class-frequency-aware classification loss weighting;
3. SGRB-DE: training-stage semantic-guided ROI-background decoupled enhancement;
4. C2f-SimAM: parameter-free attention inserted into the P3/P4 neck feature aggregation blocks;
5. MPDIoU: point-distance-penalized bounding-box regression loss.

Important implementation notes:
- SGRB-DE enhanced samples are used only in the training list. The validation split remains the original raw validation set.
- No ground-truth boxes, semantic masks, or manually specified ROI information are used during validation or inference.
- SimAM is parameter-free; MPDIoU changes the training loss only and does not increase inference-time parameters or GFLOPs.
- The script assumes that the corresponding C2f-SimAM and MPDIoU components have been registered in the local YOLOv10/Ultralytics environment.

Before running:
1. Install the same YOLOv10/Ultralytics environment used in the manuscript.
2. Register the C2f-SimAM module and the MPDIoU loss in the local implementation.
3. Update the paths in the USER CONFIG section below.

Example:
python train_and_evaluate_ours.py ours
python train_and_evaluate_ours.py m4_without_mpdiou
"""

from __future__ import annotations

import os
import sys
import json
import random
from pathlib import Path
from ultralytics import YOLO


# =============================================================================
# USER CONFIG: update these paths before reproduction
# =============================================================================

PROJECT_DIR = Path(r"D:/reproduction_runs/infrared_switchgear_detection")
LOCAL_PRETRAIN = Path(r"D:/weights/yolov10m.pt")

# Raw dataset root: must contain images/train, images/val, labels/train, labels/val
RAW_DATASET_ROOT = Path(r"D:/datasets/infrared_switchgear")

# SGRB-DE enhanced dataset root: contains training-stage enhanced images and labels.
# This folder is used only for training-list construction, not for validation or inference.
SGRB_DATASET_ROOT = Path(r"D:/datasets/infrared_switchgear_sgrb_de")

# Output files generated by this script
RAW_DATA_YAML = RAW_DATASET_ROOT / "data_raw.yaml"
TARGET_AUG_TXT = RAW_DATASET_ROOT / "train_target_aug.txt"
TARGET_AUG_DATA_YAML = RAW_DATASET_ROOT / "data_target_aug.yaml"
SGRB_TRAIN_TXT = RAW_DATASET_ROOT / "train_target_aug_sgrb_de.txt"
SGRB_DATA_YAML = RAW_DATASET_ROOT / "data_target_aug_sgrb_de.yaml"
CLASS_WEIGHT_JSON = RAW_DATASET_ROOT / "class_weights.json"
MODEL_YAML = PROJECT_DIR / "yolov10m_c2f_simam_reproduction.yaml"

# This script rewrites the official YOLOv10 YAML and replaces only the P3/P4 neck blocks.
# If a final model YAML has already been prepared, set USE_EXISTING_MODEL_YAML = True.
USE_EXISTING_MODEL_YAML = False
EXISTING_MODEL_YAML = Path(r"D:/configs/yolov10m_c2f_simam.yaml")


# =============================================================================
# Dataset and method settings reported in the manuscript
# =============================================================================

NAMES = {
    0: "ACB", 1: "CT", 2: "Connection", 3: "LA", 4: "LBS", 5: "MCCB",
    6: "MOF", 7: "PF", 8: "PT", 9: "VCB", 10: "body", 11: "core",
}

# Minority and hard classes used for targeted augmentation and weighting.
# These classes correspond to rare or more difficult categories in the infrared switchgear dataset.
HARD_CLASSES = {2, 3, 4, 7, 11}  # Connection, LA, LBS, PF, core

TARGET_AUG_PROB = {
    2: 0.20,
    3: 0.35,
    4: 0.45,
    7: 0.60,
    11: 0.30,
}

SGRB_PROB = {
    2: 0.08,
    3: 0.45,
    4: 0.55,
    7: 0.90,
    11: 0.22,
}

CLASS_WEIGHTS = [1.00, 1.00, 1.05, 1.12, 1.20, 1.00, 1.00, 1.15, 1.00, 1.00, 1.00, 1.00]

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}


# =============================================================================
# Utility functions
# =============================================================================

def path_to_posix(p: Path) -> str:
    return str(p).replace("\\", "/")


def list_images(img_dir: Path):
    if not img_dir.exists():
        raise FileNotFoundError(f"Image directory not found: {img_dir}")
    return sorted([p for p in img_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS])


def read_label_classes(label_path: Path):
    cls_set = set()
    if not label_path.exists():
        return cls_set
    for line in label_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        parts = line.strip().split()
        if len(parts) >= 5:
            try:
                cls_set.add(int(float(parts[0])))
            except ValueError:
                pass
    return cls_set


def write_dataset_yaml(path: Path, dataset_root: Path, train_entry: str, val_entry: str = "images/val"):
    path.parent.mkdir(parents=True, exist_ok=True)
    names_block = "\n".join([f"  {i}: {name}" for i, name in NAMES.items()])
    path.write_text(
        f"""path: {path_to_posix(dataset_root)}
train: {train_entry}
val: {val_entry}

nc: 12
names:
{names_block}
""",
        encoding="utf-8",
    )


def write_raw_yaml():
    write_dataset_yaml(RAW_DATA_YAML, RAW_DATASET_ROOT, "images/train", "images/val")
    print(f"[YAML] Raw dataset YAML: {RAW_DATA_YAML}")


def make_target_aug_list(img_dir: Path, label_dir: Path, out_txt: Path, max_extra_ratio: float = 0.25):
    """Construct a fixed training list for minority-class-oriented Target Aug."""
    random.seed(42)
    base_imgs = list_images(img_dir)
    base_lines = [path_to_posix(p) for p in base_imgs]
    extra_lines = []
    hard_count = {c: 0 for c in HARD_CLASSES}

    for img_path in base_imgs:
        label_path = label_dir / f"{img_path.stem}.txt"
        cls_set = read_label_classes(label_path)
        hit = cls_set & HARD_CLASSES
        if not hit:
            continue
        for c in hit:
            hard_count[c] += 1
        prob = max(TARGET_AUG_PROB.get(c, 0.0) for c in hit)
        if random.random() < prob:
            extra_lines.append(path_to_posix(img_path))

    max_extra = int(max_extra_ratio * len(base_lines))
    if len(extra_lines) > max_extra:
        extra_lines = random.sample(extra_lines, max_extra)

    final_lines = base_lines + extra_lines
    random.shuffle(final_lines)
    out_txt.parent.mkdir(parents=True, exist_ok=True)
    out_txt.write_text("\n".join(final_lines), encoding="utf-8")

    print("=" * 80)
    print(f"[Target Aug] base images: {len(base_lines)}")
    print(f"[Target Aug] duplicated/minority-oriented entries: {len(extra_lines)}")
    print(f"[Target Aug] final training entries: {len(final_lines)}")
    for c in sorted(hard_count):
        print(f"  {c:>2} {NAMES[c]:<12}: {hard_count[c]}")
    print(f"[Target Aug] training list saved to: {out_txt}")
    print("=" * 80)


def write_target_aug_yaml():
    make_target_aug_list(
        img_dir=RAW_DATASET_ROOT / "images" / "train",
        label_dir=RAW_DATASET_ROOT / "labels" / "train",
        out_txt=TARGET_AUG_TXT,
        max_extra_ratio=0.25,
    )
    write_dataset_yaml(TARGET_AUG_DATA_YAML, RAW_DATASET_ROOT, path_to_posix(TARGET_AUG_TXT), "images/val")
    print(f"[YAML] Target Aug dataset YAML: {TARGET_AUG_DATA_YAML}")


def write_sgrb_training_yaml():
    """Add pre-generated SGRB-DE enhanced training samples to the fixed training list.

    This function implements the training-stage use of SGRB-DE in the reproducibility script.
    The validation set remains the raw validation set, avoiding label leakage.
    """
    enhanced_img_dir = SGRB_DATASET_ROOT / "images" / "train"
    enhanced_label_dir = SGRB_DATASET_ROOT / "labels" / "train"

    if not TARGET_AUG_TXT.exists():
        raise FileNotFoundError(f"Target Aug list not found: {TARGET_AUG_TXT}")

    if not enhanced_img_dir.exists() or not enhanced_label_dir.exists():
        print("[WARNING] SGRB-DE enhanced training images/labels were not found.")
        print("[WARNING] Falling back to Target Aug data YAML.")
        return str(TARGET_AUG_DATA_YAML)

    random.seed(42)
    base_lines = [x.strip() for x in TARGET_AUG_TXT.read_text(encoding="utf-8").splitlines() if x.strip()]
    enhanced_imgs = list_images(enhanced_img_dir)
    sgrb_extra_lines = []
    hard_count = {c: 0 for c in HARD_CLASSES}

    for img_path in enhanced_imgs:
        label_path = enhanced_label_dir / f"{img_path.stem}.txt"
        cls_set = read_label_classes(label_path)
        hit = cls_set & HARD_CLASSES
        if not hit:
            continue
        for c in hit:
            hard_count[c] += 1
        prob = max(SGRB_PROB.get(c, 0.0) for c in hit)
        if random.random() < prob:
            sgrb_extra_lines.append(path_to_posix(img_path))

    # The number follows the manuscript experiment setting: approximately 10% of the original training images.
    max_sgrb_extra = int(0.10 * 4421)
    if len(sgrb_extra_lines) > max_sgrb_extra:
        sgrb_extra_lines = random.sample(sgrb_extra_lines, max_sgrb_extra)

    final_lines = base_lines + sgrb_extra_lines
    random.shuffle(final_lines)
    SGRB_TRAIN_TXT.write_text("\n".join(final_lines), encoding="utf-8")
    write_dataset_yaml(SGRB_DATA_YAML, RAW_DATASET_ROOT, path_to_posix(SGRB_TRAIN_TXT), "images/val")

    print("=" * 80)
    print(f"[SGRB-DE] Target Aug entries: {len(base_lines)}")
    print(f"[SGRB-DE] enhanced training entries: {len(sgrb_extra_lines)}")
    print(f"[SGRB-DE] final training entries: {len(final_lines)}")
    for c in sorted(hard_count):
        print(f"  {c:>2} {NAMES[c]:<12}: {hard_count[c]}")
    print(f"[SGRB-DE] mixed training YAML: {SGRB_DATA_YAML}")
    print("=" * 80)
    return str(SGRB_DATA_YAML)


def write_class_weight_json():
    CLASS_WEIGHT_JSON.parent.mkdir(parents=True, exist_ok=True)
    out = {
        "weights": CLASS_WEIGHTS,
        "note": "Class-frequency-aware weights used for long-tailed distribution mitigation.",
        "hard_classes": {"2": "Connection", "3": "LA", "4": "LBS", "7": "PF", "11": "core"},
    }
    CLASS_WEIGHT_JSON.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"[Class Weight] JSON saved to: {CLASS_WEIGHT_JSON}")


def find_official_yolov10_yaml() -> Path | None:
    import ultralytics
    root = Path(ultralytics.__file__).resolve().parent
    candidates = [
        root / "cfg" / "models" / "v10" / "yolov10.yaml",
        root / "cfg" / "models" / "v10" / "yolov10m.yaml",
        root / "cfg" / "models" / "10" / "yolov10.yaml",
    ]
    for p in candidates:
        if p.exists():
            return p
    return None


def write_c2f_simam_model_yaml():
    """Generate a YOLOv10m YAML with C2f-SimAM/C2fCIB-SimAM in the P3/P4 neck blocks."""
    if USE_EXISTING_MODEL_YAML:
        if not EXISTING_MODEL_YAML.exists():
            raise FileNotFoundError(f"Existing model YAML not found: {EXISTING_MODEL_YAML}")
        return str(EXISTING_MODEL_YAML)

    official = find_official_yolov10_yaml()
    if official is None:
        raise FileNotFoundError("Cannot find the official YOLOv10 YAML in the installed Ultralytics package.")

    text = official.read_text(encoding="utf-8", errors="ignore")
    lines = []
    for line in text.splitlines():
        if line.strip().startswith("nc:"):
            lines.append("nc: 12")
        else:
            lines.append(line)
    text = "\n".join(lines)

    # Neck P3: replace the official C2f block with C2f_SimAM.
    if "  - [-1, 3, C2f, [256]]" in text:
        text = text.replace("  - [-1, 3, C2f, [256]]", "  - [-1, 3, C2f_SimAM, [256]]", 1)
    else:
        raise RuntimeError("Cannot find the official P3 neck block: - [-1, 3, C2f, [256]]")

    # Neck P4: replace C2fCIB with C2fCIB_SimAM while preserving official arguments.
    p4_patterns = [
        "  - [-1, 3, C2fCIB, [512, True]]",
        "  - [-1, 3, C2fCIB, [512, True, False]]",
        "  - [-1, 3, C2fCIB, [512]]",
    ]
    replaced = False
    for pat in p4_patterns:
        if pat in text:
            text = text.replace(pat, pat.replace("C2fCIB", "C2fCIB_SimAM"), 1)
            replaced = True
            break
    if not replaced:
        raise RuntimeError("Cannot find the official P4 C2fCIB neck block.")

    MODEL_YAML.parent.mkdir(parents=True, exist_ok=True)
    MODEL_YAML.write_text(text + "\n", encoding="utf-8")
    print(f"[Model YAML] official source: {official}")
    print(f"[Model YAML] C2f-SimAM reproduction model: {MODEL_YAML}")
    return str(MODEL_YAML)


def prepare_experiments():
    PROJECT_DIR.mkdir(parents=True, exist_ok=True)
    write_raw_yaml()
    write_target_aug_yaml()
    write_class_weight_json()
    model_yaml = write_c2f_simam_model_yaml()
    sgrb_data_yaml = write_sgrb_training_yaml()

    return {
        "ours": {
            "name": "Ours_TargetAug_ClassWeight_SGRBDE_C2fSimAM_MPDIoU",
            "data": sgrb_data_yaml,
            "model_yaml": model_yaml,
            "mpdiou": True,
            "class_weight": True,
        },
        "m4_without_mpdiou": {
            "name": "M4_TargetAug_ClassWeight_SGRBDE_C2fSimAM",
            "data": sgrb_data_yaml,
            "model_yaml": model_yaml,
            "mpdiou": False,
            "class_weight": True,
        },
    }


def train_one(exp_key: str):
    experiments = prepare_experiments()
    if exp_key not in experiments:
        print("Available experiments:")
        for k in experiments:
            print(f"  {k}")
        raise ValueError(f"Unknown experiment: {exp_key}")

    cfg = experiments[exp_key]

    # These environment variables are used by the modified YOLOv10/Ultralytics implementation.
    os.environ["ULTRA_USE_MPDIoU"] = "1" if cfg["mpdiou"] else "0"
    if cfg["class_weight"]:
        os.environ["ULTRA_CLASS_WEIGHTS_JSON"] = str(CLASS_WEIGHT_JSON)
    else:
        os.environ.pop("ULTRA_CLASS_WEIGHTS_JSON", None)

    print("=" * 80)
    print(f"Running experiment: {exp_key}")
    print(f"Name: {cfg['name']}")
    print(f"Data YAML: {cfg['data']}")
    print(f"Model YAML: {cfg['model_yaml']}")
    print(f"MPDIoU enabled: {cfg['mpdiou']}")
    print(f"Class Weight enabled: {cfg['class_weight']}")
    print("=" * 80)

    model = YOLO(str(cfg["model_yaml"])).load(str(LOCAL_PRETRAIN))

    model.train(
        data=cfg["data"],
        epochs=100,
        imgsz=640,
        batch=12,
        device="0",
        project=str(PROJECT_DIR),
        name=cfg["name"],
        optimizer="AdamW",
        lr0=0.001,
        momentum=0.937,
        weight_decay=0.0005,
        amp=True,
        seed=42,
        deterministic=False,
        cache=False,
        workers=8,
        plots=True,
        save=True,
        patience=20,
    )


def main():
    if len(sys.argv) < 2:
        print("Please specify an experiment key.")
        print("Available experiments: ours, m4_without_mpdiou")
        sys.exit(1)
    train_one(sys.argv[1])


if __name__ == "__main__":
    main()
